### ISSUE TITLE
infografía pdf

### ISSUE THREAD

**Issue by Edwin38H** [SistemasTecTlaxiaco/infografia-Edwin38H-1#1]
[infografia_Edwin_Heras.pdf](https://github.com/SistemasTecTlaxiaco/infografia-Edwin38H-1/files/8055020/infografia_Edwin_Heras.pdf)

**Comment by Yabin-2021** [comment]
Calificación **20 %**

**Comment by josealfredo79** [comment]
Bien hecho y revisado
